### ISSUE TITLE
Use ‘ref’ instead of document.querySelector

### ISSUE THREAD

**Issue by jameshulse** [sunil-sandhu/vue-todo#2]
It’ll be a bit more maintainable to use vues ref functionality for dealing directly with the input html element. Or better yet, bind it’s value to a data value and clear that.

**Comment by sunil-sandhu** [comment]
Hi @jameshulse - thank you for your suggestion. Would you mind making an update to the source code for this? It would be much appreciated and I'll be sure to reference you in the Vue/React comparison article. Thanks :)

**Comment by jameshulse** [comment]
Sure thing. Will do when I get back next week. Just created this issue from my phone at the airport ;)

**Comment by sunil-sandhu** [comment]
Hi again @jameshulse. Just wanted to let you know that I have updated the code to utilise v-model instead. Do feel free to make further updates though if you reckon the use of $refs would still make the codebase more robust. Ultimately I want the article to still feel as accessible to new developers as possible, so if you do happen to make updates, it would be amazing if you could add some comments to explain why the use of $refs is useful, so that I can add it to the article - accrediting you of course :)

**Comment by DanCharousek** [comment]
Isn't it duplicate to #1?

**Comment by sunil-sandhu** [comment]
My impression would be that in the case of this simple ToDo app, v-model is sufficient enough and requires very little code for it to work. I'm happy to leave this open for now though for you both to discuss :)

**Comment by jameshulse** [comment]
Nice one :)
